//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionContactsEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brother : Person
    {
        public string Poste { get; set; }
        public string Fonction { get; set; }
    }
}
